# Generated by Django 5.1.6 on 2025-02-19 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='assistants',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Número de asistentes'),
        ),
    ]
