# Generated by Django 5.1.6 on 2025-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
