# Generated by Django 5.1.6 on 2025-02-19 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['date'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='assistants',
            field=models.SmallIntegerField(default=1, verbose_name='Número de asistentes'),
        ),
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de formación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Nombre de formador'),
            preserve_default=False,
        ),
    ]
