# Generated by Django 5.1.6 on 2025-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_remove_page_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(verbose_name='Fecha de formación'),
        ),
    ]
